version: "2.3"

networks:
  mysql:
    name: mysql
  proxy:
    name: proxy
  traefik:
    name: traefik

services:
  mysql:
    image: mysql:5.7
    command:
      - "mysqld"
      - "--sql_mode="
      - "--innodb_buffer_pool_size=1G"
      - "--innodb_log_file_size=256M"
      - "--innodb_flush_log_at_trx_commit=1"
      - "--innodb_flush_method=O_DIRECT"
    environment: ["MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?please set mysql root password}"]
    volumes: ["./data/mysql/lib:/var/lib/mysql"]
    networks:
      mysql:
        aliases:
          - mysql5
          - mysql57
    restart: unless-stopped
    labels: ["traefik.enable=false"]
    mem_limit: 1G
    memswap_limit: 1100M
    ports: ["127.0.0.1:3306:3306"]
    logging: {driver: json-file, options: {max-file: '30', max-size: 1024k}}
    scale: ${SCALE_MYSQL:-1}

  mysql80:
    image: mysql:8.0
    command:
      - "mysqld"
      - "--sql_mode="
      - "--innodb_buffer_pool_size=1G"
      - "--innodb_log_file_size=256M"
      - "--innodb_flush_log_at_trx_commit=1"
      - "--innodb_flush_method=O_DIRECT"
      - "--default-authentication-plugin=mysql_native_password"
      - "--skip-log-bin"
      - "--server-id=1"
    environment: ["MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?please set mysql root password}"]
    volumes: ["./data/mysql80/lib:/var/lib/mysql"]
    networks:
      mysql:
        aliases:
          - mysql8
    restart: unless-stopped
    labels: ["traefik.enable=false"]
    mem_limit: 1G
    memswap_limit: 1100M
    ports: ["127.0.0.1:3308:3306"]
    logging: {driver: json-file, options: {max-file: '30', max-size: 1024k}}
    scale: ${SCALE_MYSQL80:-1}

  # traefik:
  #   image: traefik
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #     - "./config/traefik.toml:/traefik.toml:ro"
  #     - "./certs/:/certs/:ro" # run ./hosts_certs to create certificates for /etc/hosts first!
  #     - type: tmpfs
  #       target: /tmp
  #   ports: ["127.0.0.1:8080:8080", "127.0.0.1:80:80", "127.0.0.1:443:443"]
  #   networks: ["proxy", "traefik"]
  #   restart: unless-stopped
  #   mem_limit: 200M
  #   memswap_limit: 250M

  nginx:
    image: webvariants/nginx-acme-and-more
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/:ro
      - ./htpasswd/:/etc/nginx/htpasswd/:ro
      - ./certs/:/etc/nginx/certs/:ro
      - ./dhparam.pem:/etc/nginx/dhparam/dhparam.pem:ro
      - ./log:/var/log/nginx
      - ./html:/html:ro
    tmpfs:
      - /tmp
    ports: ["${NGINX_BIND:-127.0.0.1}:80:80", "${NGINX_BIND:-127.0.0.1}:443:443"]
    networks: ["proxy", "traefik"]
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    mem_limit: 512M
    memswap_limit: 513M
    logging: {driver: json-file, options: {max-file: '100', max-size: 1024k}}
    scale: ${SCALE_NGINX:-1}

  nginx-dconf:
    build:
      context: .
      dockerfile: Dockerfile.nginx-dconf
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./conf.d/:/etc/nginx/conf.d/
      - ./htpasswd/:/etc/nginx/htpasswd/
      - ./nginx-dconf:/etc/nginx/nginx-dconf:ro
      - ./html:/html
      - ./hosts.export/:/hosts.export/
    tmpfs:
      - /tmp
    working_dir: /etc/nginx/
    user: 101:${DOCKER_GID:?please run ./init first}
    restart: unless-stopped
    mem_limit: 200M
    memswap_limit: 250M
    logging: {driver: json-file, options: {max-file: '3', max-size: 512k}}
    scale: ${SCALE_NGINX_DCONF:-1}

  mail:
    image: djfarrelly/maildev
    labels: ["traefik.port=80", "traefik.enable=true", "traefik.docker.network=proxy"]
    restart: unless-stopped
    mem_limit: 50M
    memswap_limit: 100M
    networks:
      proxy:
        aliases:
          - maildev
    logging: {driver: json-file, options: {max-file: '3', max-size: 512k}}
    scale: ${SCALE_MAIL:-1}

  portainer:
    image: portainer/portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./data/portainer/data:/data"
    labels: ["traefik.port=9000", "traefik.enable=true", "traefik.docker.network=proxy"]
    restart: unless-stopped
    mem_limit: 100M
    memswap_limit: 200M
    networks: ["proxy"]
    logging: {driver: json-file, options: {max-file: '3', max-size: 512k}}
    scale: ${SCALE_PORTAINER:-1}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: phpmyadmin
    environment:
#     - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql57,mysql80
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD:?please set mysql root password}
    restart: unless-stopped
    volumes:
      - ./data/phpmyadmin/sessions:/sessions
    labels: ["traefik.port=80", "traefik.enable=true", "traefik.docker.network=proxy"]
    networks: ["mysql", "proxy"]
    logging: {driver: json-file, options: {max-file: '3', max-size: 512k}}
    scale: ${SCALE_PHPMYADMIN:-1}

  mongo-xh:
    image: percona/percona-server-mongodb:3.6
    restart: unless-stopped
    # (case sensitive) engine: mmapv1, rocksdb, wiredTiger, inMemory
    command: --storageEngine=inMemory --setParameter diagnosticDataCollectionEnabled=false
    environment:
      - MONGO_INITDB_DATABASE=xhprof
    volumes:
      - ./xhgui.js:/docker-entrypoint-initdb.d/xhgui.js:ro
    tmpfs:
      - /data/db:mode=700,size=100k,uid=1001,gid=0
    networks: ["proxy"]
    logging: {driver: json-file, options: {max-file: '3', max-size: 512k}}
    scale: ${SCALE_MONGO_XH:-1}

  xhgui:
    image: webvariants/php:7.3
    restart: unless-stopped
    depends_on:
        - mongo-xh
    tmpfs:
      - /xhgui/cache:mode=770,size=500k,uid=33,gid=33
      - /xhgui/data:mode=770,size=100k,uid=33,gid=33
    volumes:
      - ./xhgui_index_cap.php:/start/index_cap.php:ro
    networks:
      - proxy
      - default
    mem_limit: 200m
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    user: www-data:www-data
    working_dir: /xhgui
    environment:
      PHP_IMAGE_VERSION: "2"
      WEB_ROOT: "/xhgui/webroot"
      APP_DATA: "/xhgui/data"
      XHGUI_CACHE: "/xhgui/cache"
      PHP_OPCACHE_INI: "1"
      PHP_OPCACHE_INI_FAST_SHUTDOWN: "1"
      PHPINI_OPCACHE__VALIDATE_TIMESTAMPS: 0
      START_SCRIPT_DIR: /start
      XHGUI_INDEX_CAP: 104857600 # 100 MB
    labels: ["traefik.port=80", "traefik.enable=true", "traefik.docker.network=proxy"]
    logging: {driver: json-file, options: {max-file: '3', max-size: 512k}}
    scale: ${SCALE_XHGUI:-1}
